package bps

// 诊断仅保留固定错误码；未知字符串不可进入响应头或日志。
func safeBridgeErrorCode(code string) string {
	switch code {
	case "invalid_stream_options", "unsupported_stream_options":
		return code
	case "attachment_encoding_failed":
		return code
	case "attachment_transport_failed":
		return code
	case "attachment_upload_failed":
		return code
	case "bps_invalid_content_type":
		return code
	case "bps_transport_failed":
		return code
	case "bridge_authentication_failed":
		return code
	case "bridge_capacity":
		return code
	case "bridge_configuration_error":
		return code
	case "bridge_request_too_large":
		return code
	case "client_disconnected":
		return code
	case "continuation_requires_v2":
		return code
	case "event_too_large":
		return code
	case "hosted_tool_not_implemented":
		return code
	case "image_too_large":
		return code
	case "incomplete_stream":
		return code
	case "invalid_account_proxy":
		return code
	case "invalid_attachment_endpoint":
		return code
	case "invalid_attachment_response":
		return code
	case "invalid_bridge_envelope":
		return code
	case "invalid_history_cache":
		return code
	case "invalid_image":
		return code
	case "invalid_image_role":
		return code
	case "invalid_input":
		return code
	case "invalid_instructions":
		return code
	case "invalid_max_output_tokens":
		return code
	case "invalid_model":
		return code
	case "invalid_previous_response_id":
		return code
	case "invalid_reasoning":
		return code
	case "invalid_request":
		return code
	case "invalid_scope":
		return code
	case "invalid_text_config":
		return code
	case "invalid_text_format":
		return code
	case "invalid_tool_call":
		return code
	case "invalid_tool_choice":
		return code
	case "invalid_tool_name":
		return code
	case "invalid_tool_schema":
		return code
	case "invalid_tools":
		return code
	case "invalid_upstream_response":
		return code
	case "invalid_upstream_stream":
		return code
	case "method_not_allowed":
		return code
	case "previous_response_not_found":
		return code
	case "response_too_large":
		return code
	case "too_many_images":
		return code
	case "too_many_tools":
		return code
	case "tool_schema_too_large":
		return code
	case "unsupported_continuation":
		return code
	case "unsupported_encrypted_agent_message":
		return code
	case "unsupported_image_reference":
		return code
	case "unsupported_image_type":
		return code
	case "unsupported_model":
		return code
	case "unsupported_reasoning_effort":
		return code
	case "unsupported_request_field":
		return code
	case "unsupported_service_tier":
		return code
	case "unsupported_store":
		return code
	case "unsupported_text_format":
		return code
	case "upstream_response_failed":
		return code
	default:
		return "unclassified_bridge_error"
	}
}
